kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:f0c103b4550bd6b84fa4cdd3abb04ab63c13a0a8
  - linuxkit/runc:f01b88c7033180d50ae43562d72707c6881904e4
  - linuxkit/containerd:de1b18eed76a266baa3092e5c154c84f595e56da
  - linuxkit/ca-certificates:c1c73ef590dffb6a0138cf758fe4a4305c9864f4
onboot:
  - name: sysctl
    image: linuxkit/sysctl:725c1cb15fbb210cb9a7530b3a1edb233a4f6361
  - name: sysfs
    image: linuxkit/sysfs:bd556d972659f28584c4751d49fce4ae53aa714c
  - name: dhcpcd
    image: linuxkit/dhcpcd:52d2c4df0311b182e99241cdc382ff726755c450
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: format
    image: linuxkit/format:7efa07559dd23cb4dbebfd3ab48c50fd33625918
  - name: mount
    image: linuxkit/mount:c151655f56a3cb0eab6f74873bf1412eb0187c3f
    command: ["/usr/bin/mountie", "/var/lib/docker"]
services:
#  - name: termina-services
#    image: termina-services
#    capabilities:
#      - all
#    net: host
  - name: getty
    image: linuxkit/getty:c9d5afa9a61ac907904090643e946874ff6bf07c-amd64
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:4f85d8de3f6f45973a8c88dc8fba9ec596e5495a
  - name: ntpd
    image: linuxkit/openntpd:d6c36ac367ed26a6eeffd8db78334d9f8041b038
  - name: docker
    image: docker:20.10.6-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /var/run:/var/run
     - /etc/html:/var/html
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
  - name: compose
    image: linuxkitprojects/compose:111f9f32a933c9e7acbf3ccfc13fedbdfce8224f
    binds:
     - /var/run:/var/run
     - /etc/compose:/compose
files:
  - path: var/lib/docker
    directory: true
  - path: etc/html/a/index.html
    source: html-a.html
  - path: etc/html/b/index.html
    source: html-b.html
  - path: etc/compose/docker-compose.yml
    source: docker-compose.yml
#  - path: etc/compose/images/termina-services.tar
#    source: image-cache/termina-services.tar
trust:
  org:
    - linuxkit
    - library
